#!/bin/bash
# We use exe() to echo commands as we execute them.
exe() { echo "\$ $@" ; "$@" ; }

# Use 'set -e' so that if any of commands fail, the script will exit.
set -e

TRACE_DIR=$(ls $TRACES_PATH | grep drmemtrace | head -n 1)
echo "The trace is in $TRACE_DIR"

# Run Scarab
echo Starting Scarab
exe scarab  \
        --output_dir $SCARAB_OUT_PATH \
        --frontend memtrace  \
        --inst_limit 500000 \
        --fetch_off_path_ops 0 \
        --cbp_trace_r0=$TRACES_PATH/$TRACE_DIR/trace \
        --memtrace_modules_log=$TRACES_PATH/$TRACE_DIR/bin

echo Finished Scarab